apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: bradkim
spec:
  # type: ClusterIP 
  # 생략시 default는 ClusterIP.
  # NodePort, LoadBalancer등의 타입을 사용시 service를 통해 외부접근가능
  ports:
  - port: 80 #this is service port 80
    targetPort: 80 # this is pod inner port 80
  selector:
    app: my-nginx #need to same with labels of pod
  