apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: bradkim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx # this will watch pod with this label 
  template:
    metadata:
      labels:
        app: my-nginx # this will labelling pods
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bradkim
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx #