name: deploy order order-backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2 # checkout my github repo
      
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install
        
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }} 
          aws-secret-access-key:  ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name  my-cluster --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image to ecr
        env:
          REGISTRY: 565319458549.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: order-backend
          IMAGE_TAG: latest
        run: |
          docker buildx build \
          --platform linux/amd64 \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./2.ordersystem/Dockerfile ./2.ordersystem \
          --push

      - name: eks kubectl apply
        run: |
          kubectl rollout restart deployment ordersystem-backend -n bradkim
        # kubectl apply -f ./2.ordersystem/k8s/k8s-ordersystem/depl_svc.yml